//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborServices.ViewModel.Resources.WestWindResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborServices.ViewModel.Resources.WestWindResources.DalalResources", typeof(DalalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address_Description {
            get {
                return ResourceManager.GetString("Address Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثال: بجوار مدرسة .....
        /// </summary>
        public static string Address_Description_PH {
            get {
                return ResourceManager.GetString("Address Description PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيام المتاحة.
        /// </summary>
        public static string AvaialbleDays {
            get {
                return ResourceManager.GetString("AvaialbleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل بنكي.
        /// </summary>
        public static string BankTransfer {
            get {
                return ResourceManager.GetString("BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع ملف التحويل البنكي بنجاح.
        /// </summary>
        public static string BankTransferIsUploaded {
            get {
                return ResourceManager.GetString("BankTransferIsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع صورة التحويل البنكي من قبل!.
        /// </summary>
        public static string BankTransferIsUploadedBefore {
            get {
                return ResourceManager.GetString("BankTransferIsUploadedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العقد ملغى .. إذا كانت تواجهك مشكلة برجاء التواصل معنا.
        /// </summary>
        public static string CancelledContractMsg {
            get {
                return ResourceManager.GetString("CancelledContractMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر موقع الزيارة.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفترة.
        /// </summary>
        public static string ChoosePackage {
            get {
                return ResourceManager.GetString("ChoosePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر طريقة الدفع.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مدينة.
        /// </summary>
        public static string City_PH {
            get {
                return ResourceManager.GetString("City_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشاط الشركة.
        /// </summary>
        public static string CompanyActivity {
            get {
                return ResourceManager.GetString("CompanyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ممثل الشركة.
        /// </summary>
        public static string companyRep {
            get {
                return ResourceManager.GetString("companyRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرًا لكم .. تم تسجيل التعاقد بنجاح.
        /// </summary>
        public static string Contract_FinishRequestAlert {
            get {
                return ResourceManager.GetString("Contract_FinishRequestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر النهائي.
        /// </summary>
        public static string Contract_NetPackagePrice {
            get {
                return ResourceManager.GetString("Contract_NetPackagePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الباقة بعد الخصم.
        /// </summary>
        public static string Contract_PackagePriceAfterDiscount {
            get {
                return ResourceManager.GetString("Contract_PackagePriceAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        public static string ContractBasicInfo {
            get {
                return ResourceManager.GetString("ContractBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة التعاقد.
        /// </summary>
        public static string ContractDuration {
            get {
                return ResourceManager.GetString("ContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مدة التعاقد.
        /// </summary>
        public static string ContractDuration_PH {
            get {
                return ResourceManager.GetString("ContractDuration_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العقد ملغى!.
        /// </summary>
        public static string ContractIsCancelled {
            get {
                return ResourceManager.GetString("ContractIsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم طلب عاملات بالساعة.
        /// </summary>
        public static string ContractRequestHeader {
            get {
                return ResourceManager.GetString("ContractRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string CreateComplaintButton {
            get {
                return ResourceManager.GetString("CreateComplaintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;my-3 h5 text-dark&quot;&gt;
        ///                                        &lt;span class=&quot;text-primary&quot;&gt;
        ///                                            في رمضان:
        ///                                        &lt;/span&gt;
        ///
        ///                                        &lt;ul&gt;
        ///                                            &lt;li&gt;
        ///                                                &amp;emsp;&amp;nbsp;	 التوزيع الصباحي بين 10:30 ص و  12:30 م
        ///                                            &lt;/li&gt;
        ///                                            &lt;li&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DalalAdditionalWarning {
            get {
                return ResourceManager.GetString("DalalAdditionalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;my-3 h5 text-dark&quot;&gt;
        ///                                       هذه الخدمة تقدم 
        ///                                        &lt;span class=&quot;text-primary&quot;&gt;
        ///                                       للعائلات فقط
        ///                                        &lt;/span&gt; وفي حال عدم وجود سيدة بالمنزل نعتذر عن تقديم الخدمة
        ///                                    &lt;/div&gt;.
        /// </summary>
        public static string DalalFamilyWarning {
            get {
                return ResourceManager.GetString("DalalFamilyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحي.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الحي.
        /// </summary>
        public static string District_PH {
            get {
                return ResourceManager.GetString("District_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم المنزل.
        /// </summary>
        public static string Enter_House_No {
            get {
                return ResourceManager.GetString("Enter House No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواعيد الزيارات المتوقعة.
        /// </summary>
        public static string ExpectedVisitsAppointment {
            get {
                return ResourceManager.GetString("ExpectedVisitsAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في عملية الدفع.
        /// </summary>
        public static string FailedPaymentOperation {
            get {
                return ResourceManager.GetString("FailedPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطابق.
        /// </summary>
        public static string Floor_No {
            get {
                return ResourceManager.GetString("Floor No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباقة.
        /// </summary>
        public static string Hourly_Pricing {
            get {
                return ResourceManager.GetString("Hourly Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات.
        /// </summary>
        public static string HoursNum {
            get {
                return ResourceManager.GetString("HoursNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عدد ساعات الزيارة.
        /// </summary>
        public static string HoursNum_PH {
            get {
                return ResourceManager.GetString("HoursNum_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المنزل.
        /// </summary>
        public static string House_No {
            get {
                return ResourceManager.GetString("House No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المنزل.
        /// </summary>
        public static string House_Type {
            get {
                return ResourceManager.GetString("House Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم بنجاح تقديم الطلب.
        /// </summary>
        public static string LeadCreationSuccess {
            get {
                return ResourceManager.GetString("LeadCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر جنسية.
        /// </summary>
        public static string Nationality_PH {
            get {
                return ResourceManager.GetString("Nationality_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد مواعيد للزيارة مسجلة الآن.
        /// </summary>
        public static string No_Visits_Timing_now {
            get {
                return ResourceManager.GetString("No Visits Timing now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الباقة.
        /// </summary>
        public static string PackageDetails {
            get {
                return ResourceManager.GetString("PackageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فترة الزيارة.
        /// </summary>
        public static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشقة.
        /// </summary>
        public static string PartmentNo {
            get {
                return ResourceManager.GetString("PartmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الدفع بنجاح ... شكرا لكم.
        /// </summary>
        public static string PaymentOperationDoneSuccessfully {
            get {
                return ResourceManager.GetString("PaymentOperationDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ في عملية الدفع ... برجاء المحاولة مرة أخرى.
        /// </summary>
        public static string PaymentOperationFailed {
            get {
                return ResourceManager.GetString("PaymentOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادفع اونلاين.
        /// </summary>
        public static string PayOnline {
            get {
                return ResourceManager.GetString("PayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء اختيار وسيلة الدفع المناسبة لكم للعقد.
        /// </summary>
        public static string PleaseChooseYourPreferredPaymentMethodFortheContract {
            get {
                return ResourceManager.GetString("PleaseChooseYourPreferredPaymentMethodFortheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء دفع مبلغ.
        /// </summary>
        public static string PleasePay {
            get {
                return ResourceManager.GetString("PleasePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء الدفع اونلاين للعقد.
        /// </summary>
        public static string PleasePayOnlineForContract {
            get {
                return ResourceManager.GetString("PleasePayOnlineForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرجوا من سعادتكم رفع صورة التحويل البنكى الخاص بالعقد.
        /// </summary>
        public static string PleaseUploadBankTransferStatementFortheContract {
            get {
                return ResourceManager.GetString("PleaseUploadBankTransferStatementFortheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر قبل الخصم.
        /// </summary>
        public static string Price_Before_Discount {
            get {
                return ResourceManager.GetString("Price Before Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الخصم.
        /// </summary>
        public static string PromotionCode {
            get {
                return ResourceManager.GetString("PromotionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل كود الخصم.
        /// </summary>
        public static string PromotionCodePH {
            get {
                return ResourceManager.GetString("PromotionCodePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهن المطلوبة.
        /// </summary>
        public static string rJobs {
            get {
                return ResourceManager.GetString("rJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الراتب.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر رقم الطابق.
        /// </summary>
        public static string Select_Floor_No {
            get {
                return ResourceManager.GetString("Select Floor No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع المنزل.
        /// </summary>
        public static string Select_House_Type {
            get {
                return ResourceManager.GetString("Select House Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العقد.
        /// </summary>
        public static string SelectContract {
            get {
                return ResourceManager.GetString("SelectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيام المختارة.
        /// </summary>
        public static string SelectedDays {
            get {
                return ResourceManager.GetString("SelectedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع المشكلة.
        /// </summary>
        public static string SelectProblemType {
            get {
                return ResourceManager.GetString("SelectProblemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العامل/العاملة.
        /// </summary>
        public static string SelectWorker {
            get {
                return ResourceManager.GetString("SelectWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر طريقة الدفع.
        /// </summary>
        public static string ShopperResultHeader {
            get {
                return ResourceManager.GetString("ShopperResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ أول زيارة.
        /// </summary>
        public static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوة.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (إدخال البيانات الشخصية ( في حالة عدم أكتمالها.
        /// </summary>
        public static string StepFiveDesc {
            get {
                return ResourceManager.GetString("StepFiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاطلاع على تفاصيل العقد و إتمام التعاقد.
        /// </summary>
        public static string StepFourDesc {
            get {
                return ResourceManager.GetString("StepFourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار بيانات المكان و وقت الزيارات و الأيام المتاحة و جنسية العاملات.
        /// </summary>
        public static string StepOneDesc {
            get {
                return ResourceManager.GetString("StepOneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع و التمتع بخدمتنا المميزة.
        /// </summary>
        public static string StepSixDesc {
            get {
                return ResourceManager.GetString("StepSixDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد الموقع على الخريطة و العنوان الدقيق.
        /// </summary>
        public static string StepThreeDesc {
            get {
                return ResourceManager.GetString("StepThreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جدول الزيارات المتوقع.
        /// </summary>
        public static string StepTwoDesc {
            get {
                return ResourceManager.GetString("StepTwoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظة: لديك 3 ساعات فقط للدفع , عملية إلغاء العقد تتم بشكل تلقائى.
        /// </summary>
        public static string SuccessMessageContract {
            get {
                return ResourceManager.GetString("SuccessMessageContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية دفع ناجحة.
        /// </summary>
        public static string SuccessPaymentOperation {
            get {
                return ResourceManager.GetString("SuccessPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام؟.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق على.
        /// </summary>
        public static string TermsConfirm {
            get {
                return ResourceManager.GetString("TermsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;text-align:center; font-weight:bold&quot;&gt;
        ///                   شروط وسياسات برنامج دلال
        ///                    &lt;/div&gt;
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///&lt;p&gt;
        /// 1-	يحق للعميل تأجيل موعد الزيارة التي تم سداد قيمتها ،  وذلك عن طريق تقديم طلب قبل 48 ساعة من الموعد المراد تأجيله بحد اقصى ( مرة واحد لباقة 4 زيارات ) ، (  مرتان لباقة 8 زيارات ) ، (  3 مرات لباقة 12 زيارة )              ( 4 مرات لباقة 24 زيارة ) ، ( 5 مرات لباقة 36 زيارة ) ، (  6 مرات لباقة 48 زيارة ) . مع ضرورة الالتزام بعدم انقطاع الز [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TermsData {
            get {
                return ResourceManager.GetString("TermsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط وسياسات برنامج دلال.
        /// </summary>
        public static string TermsDataTitle {
            get {
                return ResourceManager.GetString("TermsDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الإجمالي + الضريبة.
        /// </summary>
        public static string Total_Price___Vat {
            get {
                return ResourceManager.GetString("Total Price + Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر قبل الخصم.
        /// </summary>
        public static string Total_Price_Before_Discount {
            get {
                return ResourceManager.GetString("Total Price Before Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأيام.
        /// </summary>
        public static string TotalContractDuration {
            get {
                return ResourceManager.GetString("TotalContractDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الكلى.
        /// </summary>
        public static string TotalNumber {
            get {
                return ResourceManager.GetString("TotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارفع صورة التحويل البنكي.
        /// </summary>
        public static string UploadBankTransferStatement {
            get {
                return ResourceManager.GetString("UploadBankTransferStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع صورة التحويل البنكي من قبل ... إذا كانت تواجهك مشكلة برجاء التواصل.
        /// </summary>
        public static string UploadedBankTransferBeforeMsg {
            get {
                return ResourceManager.GetString("UploadedBankTransferBeforeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع ملف التحويل البنكي بنجاح ... شكرا لكم.
        /// </summary>
        public static string UploadedBankTransferMsg {
            get {
                return ResourceManager.GetString("UploadedBankTransferMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الضريبة المضافة.
        /// </summary>
        public static string Vat_Amount {
            get {
                return ResourceManager.GetString("Vat Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة المضافة (%).
        /// </summary>
        public static string Vat_Rate____ {
            get {
                return ResourceManager.GetString("Vat Rate (%)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواعيد الزيارة.
        /// </summary>
        public static string Visits_Timing {
            get {
                return ResourceManager.GetString("Visits Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الزيارات.
        /// </summary>
        public static string VisitsNum {
            get {
                return ResourceManager.GetString("VisitsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عدد الزيارات.
        /// </summary>
        public static string VisitsNum_PH {
            get {
                return ResourceManager.GetString("VisitsNum_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العاملات.
        /// </summary>
        public static string WorkersNum {
            get {
                return ResourceManager.GetString("WorkersNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عدد العمالة.
        /// </summary>
        public static string WorkersNum_PH {
            get {
                return ResourceManager.GetString("WorkersNum_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :رقم العقد خاصتكم.
        /// </summary>
        public static string YourContractNum {
            get {
                return ResourceManager.GetString("YourContractNum", resourceCulture);
            }
        }
    }
}
