//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborServices.ViewModel.Resources.WestWindResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomesticInvoiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomesticInvoiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborServices.ViewModel.Resources.WestWindResources.DomesticInvoiceResources", typeof(DomesticInvoiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة فاتورة العميل.
        /// </summary>
        public static string CustomerAmountTh {
            get {
                return ResourceManager.GetString("CustomerAmountTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير.
        /// </summary>
        public static string DomesticInvoices {
            get {
                return ResourceManager.GetString("DomesticInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string FromDateTh {
            get {
                return ResourceManager.GetString("FromDateTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة فاتورة العميل.
        /// </summary>
        public static string InvoiceAmountTh {
            get {
                return ResourceManager.GetString("InvoiceAmountTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الفاتورة.
        /// </summary>
        public static string InvoiceBasicInfo {
            get {
                return ResourceManager.GetString("InvoiceBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العقد.
        /// </summary>
        public static string InvoiceContractTh {
            get {
                return ResourceManager.GetString("InvoiceContractTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ استحقاق الفاتورة.
        /// </summary>
        public static string InvoiceDueDateTh {
            get {
                return ResourceManager.GetString("InvoiceDueDateTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدفع.
        /// </summary>
        public static string InvoiceIsPaidTh {
            get {
                return ResourceManager.GetString("InvoiceIsPaidTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string InvoiceNumberTh {
            get {
                return ResourceManager.GetString("InvoiceNumberTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الدفع.
        /// </summary>
        public static string InvoiceStatusTh {
            get {
                return ResourceManager.GetString("InvoiceStatusTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد شكاوي حالية للمستخدم..
        /// </summary>
        public static string NoInvoiceSpan {
            get {
                return ResourceManager.GetString("NoInvoiceSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        public static string ToDateTh {
            get {
                return ResourceManager.GetString("ToDateTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالى الفاتورة + النسبة.
        /// </summary>
        public static string TotalWithVatTh {
            get {
                return ResourceManager.GetString("TotalWithVatTh", resourceCulture);
            }
        }
    }
}
