//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborServices.ViewModel.Resources.WestWindResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborServices.ViewModel.Resources.WestWindResources.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن الشركة.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن الشركة.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطاع الأعمال.
        /// </summary>
        public static string BusinessSector {
            get {
                return ResourceManager.GetString("BusinessSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور؟.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقر الرئيسي : الدائري الشمالي ,حي التعاون , الرياض 12478.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور؟.
        /// </summary>
        public static string ForgetPass {
            get {
                return ResourceManager.GetString("ForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روابط قد تهمك.
        /// </summary>
        public static string ImportantLinks {
            get {
                return ResourceManager.GetString("ImportantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقوم شركة ابدال للتوظيف بتوفير عمالة منزلية تناسب طلبات الأفراد بدءاً من السائق الخاص والمعاونة المنزلية وصولاً الى الممرض/ الممرضة والطباخ الخاص والمزارع..
        /// </summary>
        public static string Individual_AbdalHeaderDesc {
            get {
                return ResourceManager.GetString("Individual_AbdalHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمـة لسـاعات محـددة وأيـام محـددة حسـب الاتفـاق مـع العميـل ، لا تتطلـب إقامـة العمالـة لـدى العميـل,يتم خلالهـا إيصـال العمالـة للعميـل علـى أن يبـدأ حسـاب وقـت الخدمـة منـذ وصـول العمالـة الـى منـزل العميـل..
        /// </summary>
        public static string Individual_DalaDescDtails {
            get {
                return ResourceManager.GetString("Individual_DalaDescDtails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة العمالة المنزلية بالساعة.
        /// </summary>
        public static string Individual_DalalTitle {
            get {
                return ResourceManager.GetString("Individual_DalalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمـة الرعايـة المنزليـة لكبـار السـن وذوي الأحتياجات الخاصـة وخدمـة المرافـق الصحـي الخـاص أو المرافقـة الصحيـة الخاصـة..
        /// </summary>
        public static string Individual_EnaihDescDetails {
            get {
                return ResourceManager.GetString("Individual_EnaihDescDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة التمريض المنزلي.
        /// </summary>
        public static string Individual_EnaihTitle {
            get {
                return ResourceManager.GetString("Individual_EnaihTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المـوارد البشـرية للعمـل فـي منـازل عائـلات المواطنـين والمقيمين، لمهـن متعـددة مـن جنسـيات مختلفـة.مع الحرص علــى توفـيـر موظفـيـن متعاقديــن مدربين ً تدريبــا ً جيــدا، يتفهمــون الثقافــة المحليــة ومتطلبــات العمــل المنزلــي. وتتحمــل الشــركة مســؤولية إدارة الموظفــن المتعاقديــن للعمــل..
        /// </summary>
        public static string Individual_TadbeerDescDetails {
            get {
                return ResourceManager.GetString("Individual_TadbeerDescDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة العمالة المنزلية بالشهر.
        /// </summary>
        public static string Individual_TadbeerTitle {
            get {
                return ResourceManager.GetString("Individual_TadbeerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمــات الوســاطة فــي اســتقدام المــوارد البشــرية المنزليــة للمنشأت التــي لديهــا تأشيــراتهم الخاصــة، حيــث تقــوم الشــركة ً بجلــب الكــوادر وفقــا لمتطلباتهــم، خــلال فتــرة زمنيــة وجيــزة..
        /// </summary>
        public static string Individual_WasatahDescDetails {
            get {
                return ResourceManager.GetString("Individual_WasatahDescDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات الوساطة في استخدام الأفراد.
        /// </summary>
        public static string Individual_WasatahTitle {
            get {
                return ResourceManager.GetString("Individual_WasatahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطاع الأفراد.
        /// </summary>
        public static string Individuals {
            get {
                return ResourceManager.GetString("Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login_Short {
            get {
                return ResourceManager.GetString("Login_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        public static string MailingList {
            get {
                return ResourceManager.GetString("MailingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string MasterContactUs {
            get {
                return ResourceManager.GetString("MasterContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطاع الطبي.
        /// </summary>
        public static string MedicalSector {
            get {
                return ResourceManager.GetString("MedicalSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابي.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروعنا.
        /// </summary>
        public static string OurBranches {
            get {
                return ResourceManager.GetString("OurBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة الشركة.
        /// </summary>
        public static string OurMissions {
            get {
                return ResourceManager.GetString("OurMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبدأ مدة الزيارة من أربع ساعات.
        /// </summary>
        public static string OurPrograms_DalalDesc {
            get {
                return ResourceManager.GetString("OurPrograms_DalalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لرعاية كبار السن وذوي الاحتياجات الخاصة (ممرضة، مرافق شخصي، ...).
        /// </summary>
        public static string OurPrograms_EnaihDesc {
            get {
                return ResourceManager.GetString("OurPrograms_EnaihDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمالة لكافة القطاعات وجميع المهن بتعاقد مرن (بالساعات، بالأيام، بالأسابيع،...).
        /// </summary>
        public static string OurPrograms_JahezDesc {
            get {
                return ResourceManager.GetString("OurPrograms_JahezDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سائق خاص، عاملة منزلية، مربية، حارس، ...
        /// </summary>
        public static string OurPrograms_TadbeerDesc {
            get {
                return ResourceManager.GetString("OurPrograms_TadbeerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برامجنـــــا.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الشخصية.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل جديد.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أشترك فى القائمة البريدية.
        /// </summary>
        public static string RegisterMailingList {
            get {
                return ResourceManager.GetString("RegisterMailingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل جديد.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
    }
}
