//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborServices.ViewModel.Resources.WestWindResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborServices.ViewModel.Resources.WestWindResources.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل بنكي.
        /// </summary>
        public static string BankTransfer {
            get {
                return ResourceManager.GetString("BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفع التحويل البنكي.
        /// </summary>
        public static string BankTransferIsUploaded {
            get {
                return ResourceManager.GetString("BankTransferIsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر طريقة الدفع.
        /// </summary>
        public static string ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى عملية دفع.
        /// </summary>
        public static string FailedPaymentOperation {
            get {
                return ResourceManager.GetString("FailedPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الفاتورة.
        /// </summary>
        public static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الفاتورة تم دفعها من قبل.
        /// </summary>
        public static string InvoiceIsPaidBefore {
            get {
                return ResourceManager.GetString("InvoiceIsPaidBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم دفع قيمة هذه الفاتورة من قبل.
        /// </summary>
        public static string InvoiceIsPaidBeforeMsg {
            get {
                return ResourceManager.GetString("InvoiceIsPaidBeforeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الدفع بنجاح.
        /// </summary>
        public static string PaymentOperationDoneSuccessfully {
            get {
                return ResourceManager.GetString("PaymentOperationDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد فشلت عملية الدفع.
        /// </summary>
        public static string PaymentOperationFailed {
            get {
                return ResourceManager.GetString("PaymentOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع عبر الأنترنت.
        /// </summary>
        public static string PayOnline {
            get {
                return ResourceManager.GetString("PayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أختر طريقة الدفع المفضة ل.
        /// </summary>
        public static string PleaseChooseYourPreferredPaymentMethodForthe {
            get {
                return ResourceManager.GetString("PleaseChooseYourPreferredPaymentMethodForthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدفع عبر الأنترنت ل.
        /// </summary>
        public static string PleasePayOnlineForThe {
            get {
                return ResourceManager.GetString("PleasePayOnlineForThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحميل بيان التحويل المصرفي ل.
        /// </summary>
        public static string PleaseUploadBankTransferStatementFortheInvoice {
            get {
                return ResourceManager.GetString("PleaseUploadBankTransferStatementFortheInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشكلة فى التحويل البنكي.
        /// </summary>
        public static string ProblemInUploadingBankTransfer {
            get {
                return ResourceManager.GetString("ProblemInUploadingBankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدثت مشكلة فى رفع التحويل البنكي.
        /// </summary>
        public static string ProblemInUploadingBankTransferMsg {
            get {
                return ResourceManager.GetString("ProblemInUploadingBankTransferMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدفع.
        /// </summary>
        public static string SuccessPaymentOperation {
            get {
                return ResourceManager.GetString("SuccessPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة الكلية.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بتحميل بيان التحويل البنكي.
        /// </summary>
        public static string UploadBankTransferStatement {
            get {
                return ResourceManager.GetString("UploadBankTransferStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم رفع التحويل البنكي بنجاح.
        /// </summary>
        public static string UploadedBankTransferMsg {
            get {
                return ResourceManager.GetString("UploadedBankTransferMsg", resourceCulture);
            }
        }
    }
}
