//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaborServices.ViewModel.Resources.WestWindResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaborServices.ViewModel.Resources.WestWindResources.ProfileResources", typeof(ProfileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن المستخدم.
        /// </summary>
        public static string AboutUserSpan {
            get {
                return ResourceManager.GetString("AboutUserSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة رقم الهاتف.
        /// </summary>
        public static string AddPhoneNumber {
            get {
                return ResourceManager.GetString("AddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما.
        /// </summary>
        public static string Anerrorhasoccurred {
            get {
                return ResourceManager.GetString("Anerrorhasoccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط هنا لتسجيل الدخول.
        /// </summary>
        public static string ClickHereToLogIn {
            get {
                return ResourceManager.GetString("ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الغلق.
        /// </summary>
        public static string ClientClosedCodeTH {
            get {
                return ResourceManager.GetString("ClientClosedCodeTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string ContactTH {
            get {
                return ResourceManager.GetString("ContactTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العقد.
        /// </summary>
        public static string ContractDateTH {
            get {
                return ResourceManager.GetString("ContractDateTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العقد.
        /// </summary>
        public static string ContractNumTH {
            get {
                return ResourceManager.GetString("ContractNumTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العقد.
        /// </summary>
        public static string ContractTH {
            get {
                return ResourceManager.GetString("ContractTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل حساب جديد.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكاوى دلال.
        /// </summary>
        public static string DalalComplaints {
            get {
                return ResourceManager.GetString("DalalComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل البيانات.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string EditProfileBtn {
            get {
                return ResourceManager.GetString("EditProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخال كود التحقق.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر النهائي.
        /// </summary>
        public static string FinalPriceTH {
            get {
                return ResourceManager.GetString("FinalPriceTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور؟.
        /// </summary>
        public static string ForgetyourpasswordLink {
            get {
                return ResourceManager.GetString("ForgetyourpasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت رقمك السرى؟.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر النوع.
        /// </summary>
        public static string Gender_PH {
            get {
                return ResourceManager.GetString("Gender_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشكاوي.
        /// </summary>
        public static string hdrComplaintsSpan {
            get {
                return ResourceManager.GetString("hdrComplaintsSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العقود.
        /// </summary>
        public static string hdrContractsSpan {
            get {
                return ResourceManager.GetString("hdrContractsSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكاوى الأفراد.
        /// </summary>
        public static string IndividualsComplaints {
            get {
                return ResourceManager.GetString("IndividualsComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوظيفي.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الحساب الخاص بك.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأوسط.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السرى الجديد.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد شكاوي حالية للمستخدم..
        /// </summary>
        public static string NoComplaintsSpan {
            get {
                return ResourceManager.GetString("NoComplaintsSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عقود حالية للمستخدم..
        /// </summary>
        public static string NoContractsSpan {
            get {
                return ResourceManager.GetString("NoContractsSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تسجل بعد؟ سجل الان.
        /// </summary>
        public static string NotRegisteredYetRegisterNow {
            get {
                return ResourceManager.GetString("NotRegisteredYetRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السرى القديم.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحقق من رقم الجوال بنجاح.
        /// </summary>
        public static string phonenumberverified {
            get {
                return ResourceManager.GetString("phonenumberverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر كلمة المرور.
        /// </summary>
        public static string PickPassword {
            get {
                return ResourceManager.GetString("PickPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المشكلة.
        /// </summary>
        public static string ProblemTypeTH {
            get {
                return ResourceManager.GetString("ProblemTypeTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الشخصية.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المنطقة.
        /// </summary>
        public static string Region_PH {
            get {
                return ResourceManager.GetString("Region_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرنى ؟.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد تغير كلمة المرور.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القطاع.
        /// </summary>
        public static string SectorTypeTH {
            get {
                return ResourceManager.GetString("SectorTypeTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مدينة.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر جنسية.
        /// </summary>
        public static string SelectNationality {
            get {
                return ResourceManager.GetString("SelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسال الكود عبر الرسالة النصية.
        /// </summary>
        public static string SendCodeBySms {
            get {
                return ResourceManager.GetString("SendCodeBySms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال كود التحقق.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العقد.
        /// </summary>
        public static string StatusNameTH {
            get {
                return ResourceManager.GetString("StatusNameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string StatusTH {
            get {
                return ResourceManager.GetString("StatusTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشكوى.
        /// </summary>
        public static string TicketNumberTH {
            get {
                return ResourceManager.GetString("TicketNumberTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من رقم التليفون.
        /// </summary>
        public static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير كلمة المرور الخاصة بك.
        /// </summary>
        public static string Yourpasswordhasbeenchanged {
            get {
                return ResourceManager.GetString("Yourpasswordhasbeenchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير كلمة المرور.
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين كلمة المرور الخاصة بك.
        /// </summary>
        public static string Yourpasswordhasbeenset {
            get {
                return ResourceManager.GetString("Yourpasswordhasbeenset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف رقم جوالك بنجاح.
        /// </summary>
        public static string Yourphonenumberwasremoved_ {
            get {
                return ResourceManager.GetString("Yourphonenumberwasremoved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين خاصية التحقق من عاملين.
        /// </summary>
        public static string Yourtwofactorproviderhasbeenset {
            get {
                return ResourceManager.GetString("Yourtwofactorproviderhasbeenset", resourceCulture);
            }
        }
    }
}
